//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat_App_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class natacadT
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Edad { get; set; }
        public string Grado { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string Nombre_Tutor { get; set; }
        public string Apellidos_Tutor { get; set; }
        public string Celular_Tutor { get; set; }
        public int codigo { get; set; }
        public int cantidad { get; set; }
    }
}
